### ISSUE TITLE
JSON parse issue

### ISSUE THREAD

**Issue by andersmilton** [szokeptr/homebridge-tradfri-plugin#1]
Looks nice!

Tried installing it now, but the plugin can't seem to recognise my gateway or accessories. I get the following in the Homebridge log file:

`SyntaxError: Unexpected token A in JSON at position 0
    at Object.parse (native)
    at coap.get.then (/usr/local/lib/node_modules/homebridge-tradfri/dist/tradfri/tradfri.js:23:36)
    at process._tickCallback (internal/process/next_tick.js:103:7)`

Works great with Jesper Lindbergs `homebridge-tradfri`, https://github.com/jesper-lindberg/homebridge-tradfri, so I don't think there's anything horribly wrong with my setup.

**Comment by szokeptr** [comment]
I think your issue is with Jesper Lindbergs `homebridge-tradfri` plugin, since mine is called `homebridge-tradfri-plugin`. Notice the file where the error is thrown (/usr/local/lib/node_modules/**homebridge-tradfri**/dist/tradfri/tradfri.js:23:36).

Make sure you are only running one of the plugins if you have more installed. Just remove their configuration from config.json.

**Comment by andersmilton** [comment]
I had already replaced the homebridge-tradfri configuration with the homebridge-tradfri-plugin one when I got the error. Maybe Homebridge cached it somewhere? Or maybe there was a conflict as `"name": "Tradfri"` is the same in the config for both plugins?

Anyway, good catch! I uninstalled homebridge-tradfri and now your plugin works like a charm!

**Comment by szokeptr** [comment]
I'm glad it works. I'll close this issue now, if you have some other problems feel free to reopen.

**Comment by 123rolle** [comment]
I'm getting the following: 

Mon, 17 Apr 2017 10:41:01 GMT EventedHTTPServer [::ffff:192.168.0.108] Muting event '3.10' notification for this connection since it originated here.
Mon, 17 Apr 2017 10:41:01 GMT Accessory [Homebridge] Got Characteristic "Saturation" value: 26909
Mon, 17 Apr 2017 10:41:01 GMT EventedHTTPServer [::ffff:192.168.0.108] Muting event '3.12' notification for this connection since it originated here.
(node:6316) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token v in JSON at position 0
(node:6316) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Mon, 17 Apr 2017 10:42:01 GMT EventedHTTPServer [::ffff:192.168.0.108] Client connection closed
Mon, 17 Apr 2017 10:42:01 GMT EventedHTTPServer [::ffff:192.168.0.108] HTTP connection was closed
Mon, 17 Apr 2017 10:42:01 GMT EventedHTTPServer [::ffff:192.168.0.108] HTTP server was closed

I had homebridge-ikea, but that has been uninstalled.
